// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dcxdjyadjiugewbooaol.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRjeGRqeWFkaml1Z2V3Ym9vYW9sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5Mzk2MjEsImV4cCI6MjA1OTUxNTYyMX0.KcsRVf3M3Nfg1dKVUNs3Y1Kvzk67V4jTEqI_RMWqIj4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);